#!/usr/bin/env bash
# script that install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -y allow 'Nginx HTTP'
sudo -i
echo "Holberton School" > /var/www/html/index.nginx-debian.html
