#!/usr/bin/env bash
# script that install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo -e "Ceci n'est pas une page" |sudo tee /var/www/html/custom_404.html
sudo sed -i "s/server_name _;/server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/" /etc/nginx/sites-available/default
sudo sed -i "s/http {/http {add_header X-Served-By \$HOSTNAME;/" /etc/nginx/nginx.conf
sudo service nginx restart
