#!/usr/bin/env bash
# script that install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend web-front
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 933-web-01 35.227.43.49:80 check
    server 933-web-02 35.231.164.230:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
