#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely
sudo chmod -R 777 /var/run/ 
echo $$ > /var/run/holbertonscript.pid
trap "I hate the kill command" SIGTERM
trap "Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGTERM
while true
do
	echo To infinity and beyond
	sleep 2
done
