#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
COUNTER=1
while [ $COUNTER -lt 10 ]; do
	if [ $COUNTER -eq 9 ]
	then
		echo "Hi"
	fi	
	echo "Holberton School"
	let COUNTER=COUNTER+1
done;
