#!/usr/bin/env bash
# script that displays numbers from 1 to 20
COUNTER=1
while [ $COUNTER -le 20 ]; do
	
	echo $COUNTER
	case $COUNTER in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "good luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	*)
		;;
esac
	let COUNTER=COUNTER+1
done;
