#!/usr/bin/env bash
# script that displays numbers from 1 to 20
COUNTER=1
while [ $COUNTER -le 20 ]; do
	
	echo $COUNTER
	if [ $COUNTER -eq 4 ]
	then
		echo "bad luck from China"
	
	elif [ $COUNTER -eq 9 ]
	then
		echo "good luck from Japan"
	elif [ $COUNTER -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	let COUNTER=COUNTER+1
done;
